name: Build Result
# template source: https://github.com/voting/.github/blob/main/templates/call-docker-build.yaml
on:
  push:
    branches:
      - 'main'
    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'
  pull_request:
    branches:
      - 'main'

    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'

jobs:
  call-docker-build:
    name: Result Call Docker Build
    # ⬇⬇⬇ ADD THIS LINE TO USE YOUR EC2 SELF-HOSTED RUNNER
    runs-on: [self-hosted, linux, ec2]   # <-- match your runner labels
    # uses: voting/.github/.github/workflows/reusable-docker-build.yaml@main
    permissions:
      contents: read
      packages: write      # needed to push docker image to ghcr.io
      pull-requests: write # needed for PR comments
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      dockerhub-enable: true
      ghcr-enable: true
      image-names: |
        ghcr.io/voting/example-voting-app-result
        voting/examplevotingapp_result
      tag-rules: |
        type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
        type=raw,value=before,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
        type=raw,value=after,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
        type=ref,event=pr
      context: result



      platforms: linux/amd64,linux/arm64,linux/ar
