name: Build Result
# template source: https://github.com/voting/.github/blob/main/templates/call-docker-build.yaml

on:
  push:
    branches:
      - 'main'
    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'

jobs:
  call-docker-build:

    name: Result Call Docker Build

    runs-on: [self-hosted, linux, ec2]   # <-- match your runner labels

    permissions:
      contents: read
      packages: write      # needed to push docker image to ghcr.io
      pull-requests: write # needed for PR comments

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Call reusable workflow
        uses: voting/.github/.github/workflows/reusable-docker-build.yaml@main
        with:
          dockerhub-enable: true
          ghcr-enable: true

          image-names: |
            ghcr.io/voting/example-voting-app-result
            voting/examplevotingapp_result

          tag-rules: |
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=raw,value=before,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=raw,value=after,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=pr

          context: result

          platforms: linux/amd64,linux/arm64,linux/arm/v7

          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
